---

## 🏋️ Practice Questions

> **Instructions:** Try to solve these on your own before looking at hints!  
> You can write your code in the cells provided below each question.

---

### ❓ Q1. Array Creation
Create the following arrays:
- (a) A 1D NumPy array of numbers from **5 to 50** in steps of **5** using `np.arange()`.
- (b) A 2D array of shape **(4, 4)** filled with the value **7** using `np.full()`.
- (c) An array of **8 evenly spaced values** between **0 and 1** using `np.linspace()`.

In [1]:
# Q1: Your answer here
import numpy as np
# (a) 1D array from 5 to 50 with step 5
arr1 = np.arange(5, 51, 5)
print("Array (a):")
print(arr1)

# (b) 4x4 array filled with 7
arr2 = np.full((4, 4), 7)
print("\nArray (b):")
print(arr2)

# (c) 8 evenly spaced values between 0 and 1
arr3 = np.linspace(0, 1, 8)
print("\nArray (c):")
print(arr3)


Array (a):
[ 5 10 15 20 25 30 35 40 45 50]

Array (b):
[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]

Array (c):
[0.         0.14285714 0.28571429 0.42857143 0.57142857 0.71428571
 0.85714286 1.        ]


---

### ❓ Q2. Array Attributes
Create a 2D NumPy array of shape **(5, 3)** containing your own values.  
Then print its: `ndim`, `shape`, `size`, and `dtype`.

In [2]:
import numpy as np

# Create a 5x3 array
arr = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90],
    [100, 110, 120],
    [130, 140, 150]
])

# Print array
print("Array:")
print(arr)

# Print attributes
print("\nNumber of Dimensions (ndim):", arr.ndim)
print("Shape:", arr.shape)
print("Size:", arr.size)
print("Data Type (dtype):", arr.dtype)

Array:
[[ 10  20  30]
 [ 40  50  60]
 [ 70  80  90]
 [100 110 120]
 [130 140 150]]

Number of Dimensions (ndim): 2
Shape: (5, 3)
Size: 15
Data Type (dtype): int64


---

### ❓ Q3. Indexing and Slicing (1D)
Given the array: `arr = np.array([5, 10, 15, 20, 25, 30, 35, 40, 45, 50])`

- (a) Access the **3rd element** (value 15).
- (b) Access the **last element** using negative indexing.
- (c) Slice the array to get `[20, 25, 30, 35]`.
- (d) Get every **alternate element** starting from index 0.
- (e) **Reverse** the entire array using slicing.

In [4]:
import numpy as np

# Given array
arr = np.array([5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

# (a) Access the 3rd element
print("3rd element: ", arr[2])

# (b) Access the last element using negative indexing
print("Last element: ", arr[-1])

# (c) Slice the array to get [20, 25, 30, 35]
print("Elements from index 3 to 6: ", arr[3:7])

# (d) Get every alternate element starting from index 0
print("(d) Every alternate element: ", arr[::2])

# (e) Reverse the entire array
print("(e) Reversed array: ", arr[::-1])

3rd element:  15
Last element:  50
Elements from index 3 to 6:  [20 25 30 35]
(d) Every alternate element:  [ 5 15 25 35 45]
(e) Reversed array:  [50 45 40 35 30 25 20 15 10  5]


---

### ❓ Q4. 2D Array Operations
Create this array:
```
[[10, 20, 30],
 [40, 50, 60],
 [70, 80, 90]]
```
- (a) Access the value **60**.
- (b) Get the **entire second row** (row index 1).
- (c) Get the **entire first column**.
- (d) Extract the **top-left 2×2 submatrix** (`[[10,20],[40,50]]`).

In [5]:
import numpy as np

# Create the 2D array
arr = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

# (a) Access the value 60
print("Access the value 60: ", arr[1, 2])

# (b) Get the entire second row
print("(b)", arr[1])

# (c) Get the entire first column
print("First column: ", arr[:, 0])
print(arr[:, 0])

# (d) Extract the top-left 2×2 submatrix
print("2x2 submatrix: ")
print(arr[:2, :2])

Access the value 60:  60
(b) [40 50 60]
First column:  [10 40 70]
[10 40 70]
2x2 submatrix: 
[[10 20]
 [40 50]]
