---

## 🏋️ Practice Questions

> **Instructions:** Solve all questions in the cells below.  
> Try on your own first — use the topics learned today as reference!

---

### ❓ Q1. reshape() and flatten()
- (a) Create a 1D array of numbers from **1 to 24** using `np.arange()`.
- (b) Reshape it into a **4×6** matrix.
- (c) Flatten it back to 1D using `flatten()`.
- (d) Reshape the same array into shape **(2, 3, 4)** — a 3D array.

In [1]:
import numpy as np

arr = np.arange(1, 25)
print("1D Array:")
print(arr)

matrix = arr.reshape(4, 6)
print("\n4x6 Matrix:")
print(matrix)

flat = matrix.flatten()
print("\nFlattened Array:")
print(flat)

array3d = arr.reshape(2, 3, 4)
print("\n3D Array (2x3x4):")
print(array3d)

1D Array:
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]

4x6 Matrix:
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]

Flattened Array:
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]

3D Array (2x3x4):
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


---

### ❓ Q2. ravel() vs flatten()
Create a 2D array of shape **(3, 3)** with any values.
- (a) Use `ravel()` to get a 1D version. Modify the first element to `0`. Check if the original is affected.
- (b) Use `flatten()` to get a 1D version. Modify the first element to `0`. Check if the original is affected.
- (c) Write a comment explaining what you observed.

In [2]:
import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

r = arr.ravel()
r[0] = 0

print("Original after ravel():")
print(arr)

arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

f = arr.flatten()
f[0] = 0

print("Original after flatten():")
print(arr)

Original after ravel():
[[0 2 3]
 [4 5 6]
 [7 8 9]]
Original after flatten():
[[1 2 3]
 [4 5 6]
 [7 8 9]]


---

### ❓ Q3. Random Numbers and Seed
- (a) Set seed to **100** and generate an array of **10 random integers** between 1 and 50.
- (b) Create a **3×3 matrix** of random floats between 0 and 1 using `np.random.rand()`.
- (c) Simulate **20 coin flips** (0 = Heads, 1 = Tails) using `np.random.randint()`.
- (d) Count how many Heads and Tails appeared.

In [3]:
import numpy as np

np.random.seed(100)

arr = np.random.randint(1, 51, 10)
print("Random Integers:", arr)

matrix = np.random.rand(3, 3)
print("Random Float Matrix:")
print(matrix)

coin_flips = np.random.randint(0, 2, 20)
print("Coin Flips:", coin_flips)

heads = np.sum(coin_flips == 0)
tails = np.sum(coin_flips == 1)

print("Heads:", heads)
print("Tails:", tails)

Random Integers: [ 9 25  4 40 24 16 49 11 31 35]
Random Float Matrix:
[[0.18646718 0.21010774 0.4527399 ]
 [0.87014264 0.06368104 0.62431189]
 [0.52334774 0.56229626 0.00581719]]
Coin Flips: [0 1 0 0 1 1 1 1 1 0 0 1 1 1 1 1 1 1 1 0]
Heads: 6
Tails: 14


---

### ❓ Q4. Percentiles and IQR
Given salaries (in thousands): `[22, 28, 35, 40, 42, 45, 50, 55, 60, 250]`
- (a) Compute **Q1, Q2 (Median), and Q3**.
- (b) Compute the **IQR**.
- (c) Find and print any **outliers** using the IQR method.
- (d) Compute the **90th percentile** salary.

In [4]:
import numpy as np

salaries = np.array([22, 28, 35, 40, 42, 45, 50, 55, 60, 250])

q1 = np.percentile(salaries, 25)
q2 = np.percentile(salaries, 50)
q3 = np.percentile(salaries, 75)

print("Q1:", q1)
print("Q2 (Median):", q2)
print("Q3:", q3)

iqr = q3 - q1
print("IQR:", iqr)

lower = q1 - 1.5 * iqr
upper = q3 + 1.5 * iqr

outliers = salaries[(salaries < lower) | (salaries > upper)]
print("Outliers:", outliers)

p90 = np.percentile(salaries, 90)
print("90th Percentile:", p90)

Q1: 36.25
Q2 (Median): 43.5
Q3: 53.75
IQR: 17.5
Outliers: [250]
90th Percentile: 78.99999999999993


---

### ❓ Q5. Missing Values
Given temperatures: `[28.5, np.nan, 31.0, np.nan, 29.5, 27.0, np.nan, 33.0, 30.5, 26.0]`
- (a) Count how many values are missing.
- (b) Compute the **mean, max, and min** ignoring NaN.
- (c) Replace all NaN values with the **mean temperature**.
- (d) Verify no NaN values remain.

In [5]:
import numpy as np

temps = np.array([28.5, np.nan, 31.0, np.nan, 29.5,
                  27.0, np.nan, 33.0, 30.5, 26.0])

missing = np.isnan(temps).sum()
print("Missing values:", missing)

mean_temp = np.nanmean(temps)
max_temp = np.nanmax(temps)
min_temp = np.nanmin(temps)

print("Mean temperature:", mean_temp)
print("Maximum temperature:", max_temp)
print("Minimum temperature:", min_temp)

temps = np.where(np.isnan(temps), mean_temp, temps)
print("\nArray after replacing NaN:")
print(temps)
print("\nAny NaN values remaining?", np.isnan(temps).any())

Missing values: 3
Mean temperature: 29.357142857142858
Maximum temperature: 33.0
Minimum temperature: 26.0

Array after replacing NaN:
[28.5        29.35714286 31.         29.35714286 29.5        27.
 29.35714286 33.         30.5        26.        ]

Any NaN values remaining? False


---

### ❓ Q6. Sorting
Given: `scores = np.array([88, 55, 92, 70, 45, 78, 61, 85])`  
        `names  = np.array(['Alice','Bob','Charlie','Diana','Eve','Frank','Grace','Hank'])`
- (a) Sort the scores in **ascending** order.
- (b) Sort the scores in **descending** order.
- (c) Use `np.argsort()` to print names with their scores, **sorted from highest to lowest**.
- (d) Print the **top 3 students** by score.

In [6]:
import numpy as np

scores = np.array([88, 55, 92, 70, 45, 78, 61, 85])
names = np.array(['Alice', 'Bob', 'Charlie', 'Diana', 'Eve', 'Frank', 'Grace', 'Hank'])

ascending = np.sort(scores)
print("Ascending order:", ascending)

descending = np.sort(scores)[::-1]
print("Descending order:", descending)

indices = np.argsort(scores)[::-1]

print("\nStudents sorted by score (Highest to Lowest):")
for i in indices:
    print(names[i], ":", scores[i])

print("\nTop 3 Students:")
for i in indices[:3]:
    print(names[i], ":", scores[i])

Ascending order: [45 55 61 70 78 85 88 92]
Descending order: [92 88 85 78 70 61 55 45]

Students sorted by score (Highest to Lowest):
Charlie : 92
Alice : 88
Hank : 85
Frank : 78
Diana : 70
Grace : 61
Bob : 55
Eve : 45

Top 3 Students:
Charlie : 92
Alice : 88
Hank : 85


---

### ❓ Q7. Unique Values
Given city data: `cities = np.array(['Delhi','Mumbai','Delhi','Chennai','Bangalore','Mumbai','Delhi','Kolkata','Chennai','Mumbai'])`
- (a) Find all **unique cities**.
- (b) Find how many times **each city appears**.
- (c) Find which city appears the **most**.
- (d) Count **total unique cities**.

In [7]:
import numpy as np

cities = np.array([
    'Delhi', 'Mumbai', 'Delhi', 'Chennai', 'Bangalore',
    'Mumbai', 'Delhi', 'Kolkata', 'Chennai', 'Mumbai'
])

unique_cities = np.unique(cities)
print("Unique cities:", unique_cities)

unique, counts = np.unique(cities, return_counts=True)
print("\nCity counts:")
for city, count in zip(unique, counts):
    print(city, ":", count)

most_city = unique[np.argmax(counts)]
most_count = np.max(counts)
print("\nMost frequent city:", most_city)
print("Appears:", most_count, "times")

total_unique = len(unique)
print("\nTotal unique cities:", total_unique)

Unique cities: ['Bangalore' 'Chennai' 'Delhi' 'Kolkata' 'Mumbai']

City counts:
Bangalore : 1
Chennai : 2
Delhi : 3
Kolkata : 1
Mumbai : 3

Most frequent city: Delhi
Appears: 3 times

Total unique cities: 5
