---

### ❓ Q8. NumPy with Pandas
- (a) Create a NumPy array of shape **(4, 3)** with random integers between 60 and 100 (seed=7).
- (b) Convert it to a **Pandas DataFrame** with columns `['Physics', 'Chemistry', 'Biology']` and row index `['S1','S2','S3','S4']`.
- (c) Convert the `'Chemistry'` column back to a **NumPy array**.
- (d) Apply `np.mean()`, `np.max()`, and `np.min()` on that NumPy array.

In [1]:
import numpy as np
import pandas as pd

np.random.seed(7)

arr = np.random.randint(60, 101, size=(4, 3))
print("NumPy Array:")
print(arr)

df = pd.DataFrame(
    arr,
    columns=['Physics', 'Chemistry', 'Biology'],
    index=['S1', 'S2', 'S3', 'S4']
)

print("\nDataFrame:")
print(df)

chemistry_array = df['Chemistry'].to_numpy()

print("\nChemistry NumPy Array:")
print(chemistry_array)

print("\nMean:", np.mean(chemistry_array))
print("Max:", np.max(chemistry_array))
print("Min:", np.min(chemistry_array))

NumPy Array:
[[64 85 63]
 [79 83 99]
 [88 74 83]
 [68 85 86]]

DataFrame:
    Physics  Chemistry  Biology
S1       64         85       63
S2       79         83       99
S3       88         74       83
S4       68         85       86

Chemistry NumPy Array:
[85 83 74 85]

Mean: 81.75
Max: 85
Min: 74


---

### ❓ Q9. Combined Operations
Create **50 random test scores** between 30 and 100 using `np.random.randint()` with seed=99.
- (a) Print the **mean, median, std deviation**.
- (b) Find the **25th and 75th percentile**.
- (c) Find the **top 10 scores** (hint: sort descending, take first 10).
- (d) Replace all scores **below 40** with `np.nan` (simulate absent students).
- (e) Recompute the mean using the appropriate NaN-safe function.

In [2]:
import numpy as np

np.random.seed(99)

scores = np.random.randint(30, 101, 50)

print("Scores:")
print(scores)

print("\nMean:", np.mean(scores))
print("Median:", np.median(scores))
print("Standard Deviation:", np.std(scores))

print("\n25th Percentile:", np.percentile(scores, 25))
print("75th Percentile:", np.percentile(scores, 75))

top_10 = np.sort(scores)[::-1][:10]
print("\nTop 10 Scores:")
print(top_10)

scores_nan = scores.astype(float)
scores_nan[scores_nan < 40] = np.nan

print("\nScores after replacing below 40 with NaN:")
print(scores_nan)

print("\nMean after removing NaN:", np.nanmean(scores_nan))

Scores:
[31 65 87 70 98 99 82 31 53 65 85 95 78 89 32 94 42 70 50 89 69 77 57 92
 92 47 62 51 71 49 52 56 80 89 35 42 83 31 74 41 71 63 42 41 30 53 91 41
 68 96]

Mean: 65.02
Median: 66.5
Standard Deviation: 21.300225350920588

25th Percentile: 47.5
75th Percentile: 84.5

Top 10 Scores:
[99 98 96 95 94 92 92 91 89 89]

Scores after replacing below 40 with NaN:
[nan 65. 87. 70. 98. 99. 82. nan 53. 65. 85. 95. 78. 89. nan 94. 42. 70.
 50. 89. 69. 77. 57. 92. 92. 47. 62. 51. 71. 49. 52. 56. 80. 89. nan 42.
 83. nan 74. 41. 71. 63. 42. 41. nan 53. 91. 41. 68. 96.]

Mean after removing NaN: 69.56818181818181


---

### ❓ Q10. Mini Challenge — Sales Report 🏆

A company has **monthly sales data** (in ₹ lakhs) for **4 products** over **6 months**:

```
           Jan   Feb   Mar   Apr   May   Jun
Product A:  12    15   np.nan  18    20    22
Product B:  8     10    11   np.nan  14    16
Product C:  20    18    22    25    23    np.nan
Product D:  5    np.nan  7     9     8     10
```

- (a) Count total **missing values** in the dataset.
- (b) Find the **total sales per product** (ignore missing months).
- (c) Find the **best performing product** (highest total).
- (d) Find the **average sales per month** across all products.
- (e) Reshape the sales data into **shape (2, 12)** (after filling NaN with 0).
- (f) Use `np.where()` to label each product as `"Top Seller"` if total > 90, else `"Regular"`.

In [3]:
import numpy as np
import pandas as pd

sales = np.array([
    [12, 15, np.nan, 18, 20, 22],
    [8, 10, 11, np.nan, 14, 16],
    [20, 18, 22, 25, 23, np.nan],
    [5, np.nan, 7, 9, 8, 10]
])

products = np.array(['Product A', 'Product B', 'Product C', 'Product D'])

df = pd.DataFrame(
    sales,
    index=products,
    columns=['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun']
)

print("Sales Data:")
print(df)

print("\nMissing Values:", np.isnan(sales).sum())

totals = np.nansum(sales, axis=1)
print("\nTotal Sales per Product:")
for product, total in zip(products, totals):
    print(product, ":", total)

best_product = products[np.argmax(totals)]
print("\nBest Performing Product:", best_product)

monthly_average = np.nanmean(sales, axis=0)
print("\nAverage Sales per Month:")
print(monthly_average)

sales_filled = np.nan_to_num(sales)
reshaped_sales = sales_filled.reshape(2, 12)

print("\nReshaped Sales (2,12):")
print(reshaped_sales)

labels = np.where(totals > 90, "Top Seller", "Regular")

print("\nProduct Labels:")
for product, label in zip(products, labels):
    print(product, ":", label)

Sales Data:
            Jan   Feb   Mar   Apr   May   Jun
Product A  12.0  15.0   NaN  18.0  20.0  22.0
Product B   8.0  10.0  11.0   NaN  14.0  16.0
Product C  20.0  18.0  22.0  25.0  23.0   NaN
Product D   5.0   NaN   7.0   9.0   8.0  10.0

Missing Values: 4

Total Sales per Product:
Product A : 87.0
Product B : 59.0
Product C : 108.0
Product D : 39.0

Best Performing Product: Product C

Average Sales per Month:
[11.25       14.33333333 13.33333333 17.33333333 16.25       16.        ]

Reshaped Sales (2,12):
[[12. 15.  0. 18. 20. 22.  8. 10. 11.  0. 14. 16.]
 [20. 18. 22. 25. 23.  0.  5.  0.  7.  9.  8. 10.]]

Product Labels:
Product A : Regular
Product B : Regular
Product C : Top Seller
Product D : Regular
