---

## 📌 Topic 9: Mathematical / Vectorized Operations

### 🧑‍🏫 Theory

One of NumPy's greatest powers is **vectorized operations** — applying a mathematical operation to **every element** of the array **without using a loop**.

### ➕ Arithmetic Operations

You can use standard operators `+`, `-`, `*`, `/`, `**` (power), `//` (floor division), `%` (modulo) directly on arrays.

```python
arr = np.array([1, 2, 3, 4])

arr + 10   → [11, 12, 13, 14]   # Add 10 to every element
arr * 3    → [ 3,  6,  9, 12]   # Multiply every element by 3
arr ** 2   → [ 1,  4,  9, 16]   # Square every element
```

### ➕ Element-wise Operations Between Two Arrays

When two arrays have the **same shape**, operations happen **element by element**:

```python
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

a + b  → [5, 7, 9]    # 1+4, 2+5, 3+6
a * b  → [4, 10, 18]  # 1*4, 2*5, 3*6
```

### 📐 Built-in Math Functions

NumPy has powerful built-in math functions:

| Function | What it does |
|----------|--------------|
| `np.sqrt(arr)` | Square root of each element |
| `np.abs(arr)` | Absolute value of each element |
| `np.exp(arr)` | e raised to the power of each element |
| `np.log(arr)` | Natural logarithm of each element |
| `np.round(arr, n)` | Round to n decimal places |

In [18]:
# ============================================================
# TOPIC 9 EXAMPLE: Mathematical / Vectorized Operations
# ============================================================

import numpy as np

arr = np.array([1, 2, 3, 4, 5])
print("Original Array:", arr)
print()

# --- Operations with a single number (scalar) ---
print("arr + 10 :", arr + 10)    # Add 10 to each element
print("arr - 1  :", arr - 1)     # Subtract 1 from each
print("arr * 3  :", arr * 3)     # Multiply each by 3
print("arr / 2  :", arr / 2)     # Divide each by 2
print("arr ** 2 :", arr ** 2)    # Square each element
print("arr % 2  :", arr % 2)     # Modulo (remainder when divided by 2)

print()

# --- Element-wise operations between two arrays ---
a = np.array([10, 20, 30, 40])
b = np.array([1,  2,  3,  4])

print("a:", a)
print("b:", b)
print("a + b:", a + b)    # [11, 22, 33, 44]
print("a - b:", a - b)    # [9, 18, 27, 36]
print("a * b:", a * b)    # [10, 40, 90, 160]
print("a / b:", a / b)    # [10.0, 10.0, 10.0, 10.0]

Original Array: [1 2 3 4 5]

arr + 10 : [11 12 13 14 15]
arr - 1  : [0 1 2 3 4]
arr * 3  : [ 3  6  9 12 15]
arr / 2  : [0.5 1.  1.5 2.  2.5]
arr ** 2 : [ 1  4  9 16 25]
arr % 2  : [1 0 1 0 1]

a: [10 20 30 40]
b: [1 2 3 4]
a + b: [11 22 33 44]
a - b: [ 9 18 27 36]
a * b: [ 10  40  90 160]
a / b: [10. 10. 10. 10.]


In [19]:
# ============================================================
# TOPIC 9 EXAMPLE: Built-in Math Functions
# ============================================================

import numpy as np

arr = np.array([4, 9, 16, 25, 36])
print("Array:", arr)
print()

# Square root
print("np.sqrt(arr)  :", np.sqrt(arr))

# Absolute value
neg_arr = np.array([-5, -3, 0, 2, 7])
print("np.abs(neg_arr):", np.abs(neg_arr))

# Rounding
decimals = np.array([1.234, 5.678, 9.012])
print("np.round(decimals, 1):", np.round(decimals, 1))

print()

# --- Practical Example: Grade Percentage Boost ---
raw_scores = np.array([70, 80, 55, 90, 65])
print("Raw Scores      :", raw_scores)

# Add 5 bonus marks
boosted = raw_scores + 5
print("After +5 bonus  :", boosted)

# Calculate percentage out of 110 (boosted max)
percentage = np.round((boosted / 110) * 100, 2)
print("Percentage (%)  :", percentage)

Array: [ 4  9 16 25 36]

np.sqrt(arr)  : [2. 3. 4. 5. 6.]
np.abs(neg_arr): [5 3 0 2 7]
np.round(decimals, 1): [1.2 5.7 9. ]

Raw Scores      : [70 80 55 90 65]
After +5 bonus  : [75 85 60 95 70]
Percentage (%)  : [68.18 77.27 54.55 86.36 63.64]


---

## 📌 Topic 10: Aggregation Functions

### 🧑‍🏫 Theory

**Aggregation** means summarizing a collection of numbers into a **single value**.  
NumPy provides powerful functions to compute statistics over an array.

| Function | What it computes |
|----------|-----------------|
| `np.sum()` | **Sum** of all elements |
| `np.mean()` | **Average (Mean)** of all elements |
| `np.min()` | **Minimum** (smallest) value |
| `np.max()` | **Maximum** (largest) value |
| `np.median()` | **Median** (middle value when sorted) |
| `np.std()` | **Standard Deviation** (spread of data) |
| `np.var()` | **Variance** (square of std deviation) |

---

### 🏫 Quick Definitions

- **Mean**: Add all values, divide by count. Example: Mean of [60, 80, 100] = (60+80+100)/3 = 80
- **Median**: Sort the values, pick the middle one. Example: Median of [60, 80, 100] = 80
- **Std Dev**: How far (on average) each value is from the mean. **Small std = data is close together, Large std = data is spread out**
- **Variance**: Standard Deviation squared. Another way to measure spread.

---

### 🗂️ Aggregation Along an Axis (for 2D arrays)

For 2D arrays, you can compute aggregations along:
- `axis=0` → **Down each column** (row-wise collapse)
- `axis=1` → **Across each row** (column-wise collapse)

```python
arr = [[1, 2, 3],
       [4, 5, 6]]

np.sum(arr, axis=0)  → [5, 7, 9]    # Sum of each column
np.sum(arr, axis=1)  → [6, 15]      # Sum of each row
```

In [20]:
# ============================================================
# TOPIC 10 EXAMPLE: Aggregation Functions (1D)
# ============================================================

import numpy as np

# Student test scores
scores = np.array([72, 85, 90, 60, 78, 95, 88, 55, 70, 82])
print("Scores:", scores)
print()

print("Sum      :", np.sum(scores))              # Total marks
print("Mean     :", np.mean(scores))             # Average marks
print("Minimum  :", np.min(scores))              # Lowest score
print("Maximum  :", np.max(scores))              # Highest score
print("Median   :", np.median(scores))           # Middle score (sorted)
print("Std Dev  :", np.round(np.std(scores), 2)) # How spread out the scores are
print("Variance :", np.round(np.var(scores), 2)) # Variance (std² )

print()
# Finding index of min and max
print("Index of Min score:", np.argmin(scores))  # Who got lowest?
print("Index of Max score:", np.argmax(scores))  # Who got highest?

Scores: [72 85 90 60 78 95 88 55 70 82]

Sum      : 775
Mean     : 77.5
Minimum  : 55
Maximum  : 95
Median   : 80.0
Std Dev  : 12.44
Variance : 154.85

Index of Min score: 7
Index of Max score: 5


In [21]:
# ============================================================
# TOPIC 10 EXAMPLE: Aggregation on 2D Arrays (with axis)
# ============================================================

import numpy as np

# 3 students, 4 subjects
marks = np.array([
    [80, 90, 70, 85],   # Student 0: Maths, Science, English, Hindi
    [60, 75, 88, 92],   # Student 1
    [95, 85, 78, 70]    # Student 2
])

print("Marks Table (rows=students, cols=subjects):")
print(marks)
print()

# Total of everything
print("Overall Total  :", np.sum(marks))
print("Overall Mean   :", np.mean(marks))

print()

# axis=1 → sum across each ROW (total per student)
print("Total per Student (axis=1):", np.sum(marks, axis=1))

# axis=0 → sum down each COLUMN (total per subject)
print("Total per Subject (axis=0):", np.sum(marks, axis=0))

print()

# Average per student
print("Avg per Student (axis=1) :", np.round(np.mean(marks, axis=1), 2))

# Average per subject
print("Avg per Subject (axis=0) :", np.round(np.mean(marks, axis=0), 2))

Marks Table (rows=students, cols=subjects):
[[80 90 70 85]
 [60 75 88 92]
 [95 85 78 70]]

Overall Total  : 968
Overall Mean   : 80.66666666666667

Total per Student (axis=1): [325 315 328]
Total per Subject (axis=0): [235 250 236 247]

Avg per Student (axis=1) : [81.25 78.75 82.  ]
Avg per Subject (axis=0) : [78.33 83.33 78.67 82.33]


---

## 📌 Topic 11: Boolean Masking / Filtering

### 🧑‍🏫 Theory

**Boolean masking** is a powerful way to **filter elements** from an array based on a **condition**.

Here's how it works in two steps:

**Step 1**: Apply a condition to the array → This gives you an array of `True`/`False` values (called a **boolean mask**).

```python
arr = np.array([10, 25, 5, 40, 15])
mask = arr > 15
# mask → [False, True, False, True, False]
```

**Step 2**: Use the mask to filter the original array — only `True` positions are kept:

```python
arr[mask]  → [25, 40]   # Only elements where mask is True
```

This can also be written in one line:

```python
arr[arr > 15]  → [25, 40]
```

---

### 🔗 Combining Conditions

Use `&` (AND) and `|` (OR) to combine multiple conditions.  
⚠️ Always wrap each condition in **parentheses `()`**!

```python
arr[(arr > 10) & (arr < 40)]   # Elements between 10 and 40
arr[(arr < 5) | (arr > 35)]    # Elements less than 5 OR greater than 35
```

In [ ]:
# ============================================================
# TOPIC 11 EXAMPLE: Boolean Masking / Filtering
# ============================================================

import numpy as np

scores = np.array([55, 72, 48, 90, 65, 38, 85, 77, 60, 92])
print("All Scores:", scores)
print()

# --- Step 1: Create a boolean mask ---
pass_mask = scores >= 60
print("Pass Mask (scores >= 60):", pass_mask)
# Output: [False True False True True False True True True True]

print()

# --- Step 2: Apply mask to filter ---
pass_scores = scores[pass_mask]
print("Passing Scores:", pass_scores)

# --- One-liner version ---
fail_scores = scores[scores < 60]
print("Failing Scores:", fail_scores)

print()

# --- Count of passing and failing students ---
print("Number of students who passed:", len(pass_scores))
print("Number of students who failed:", len(fail_scores))

In [ ]:
# ============================================================
# TOPIC 11 EXAMPLE: Combining Conditions
# ============================================================

import numpy as np

scores = np.array([55, 72, 48, 90, 65, 38, 85, 77, 60, 92])
print("Scores:", scores)
print()

# AND condition: Scores between 60 and 85 (Grade B students)
grade_b = scores[(scores >= 60) & (scores <= 85)]
print("Grade B (60–85):", grade_b)

# OR condition: Below 50 OR above 90 (Extremes)
extremes = scores[(scores < 50) | (scores > 90)]
print("Extremes (<50 or >90):", extremes)

# NOT condition: Scores that are NOT failing
not_failing = scores[~(scores < 60)]    # ~ means NOT
print("Not Failing (not <60):", not_failing)

print()

# Practical: Assign grade labels using boolean checks
print("Any score above 90?", np.any(scores > 90))    # True if at least one
print("All scores above 30?", np.all(scores > 30))   # True if all satisfy

---

## 📌 Topic 12: `np.where()`

### 🧑‍🏫 Theory

`np.where()` is like a **vectorized if-else statement**.  
It applies a condition element by element and returns one value if `True` and another if `False`.

### 🔤 Syntax

```python
np.where(condition, value_if_true, value_if_false)
```

### 🏫 Analogy

Think of it like checking every student's marks:

> *"If the score is 60 or more, write 'Pass'. Otherwise, write 'Fail'."*

With a regular Python loop, you'd need several lines of code.  
With `np.where()`, you do it in **one line**!

```python
np.where(scores >= 60, "Pass", "Fail")
```

---

### 📝 Two ways to use `np.where()`

**1. With condition + values** (if-else replacement):
```python
np.where(condition, true_value, false_value)
```

**2. With condition only** (returns indices where condition is True):
```python
np.where(condition)   # Returns a tuple of indices
```

In [2]:
# ============================================================
# TOPIC 12 EXAMPLE: np.where()
# ============================================================

import numpy as np

scores = np.array([55, 72, 48, 90, 65, 38, 85, 77, 60, 92])
print("Scores:", scores)
print()

# --- Basic np.where(): Pass or Fail ---
result = np.where(scores >= 60, "Pass", "Fail")
print("Pass/Fail Result:", result)

print()

# --- Replace values using np.where() ---
# Apply +5 bonus to students who failed (scored < 60), leave others unchanged
adjusted = np.where(scores < 60, scores + 5, scores)
print("Original Scores :", scores)
print("Adjusted Scores  :", adjusted)  # Only failing students get +5

print()

# --- Assign Grade Labels ---
grades = np.where(scores >= 85, "A",
         np.where(scores >= 70, "B",
         np.where(scores >= 60, "C", "F")))

print("Scores:", scores)
print("Grades :", grades)

Scores: [55 72 48 90 65 38 85 77 60 92]

Pass/Fail Result: ['Fail' 'Pass' 'Fail' 'Pass' 'Pass' 'Fail' 'Pass' 'Pass' 'Pass' 'Pass']

Original Scores : [55 72 48 90 65 38 85 77 60 92]
Adjusted Scores  : [60 72 53 90 65 43 85 77 60 92]

Scores: [55 72 48 90 65 38 85 77 60 92]
Grades : ['F' 'B' 'F' 'A' 'C' 'F' 'A' 'B' 'C' 'A']


In [5]:
# ============================================================
# TOPIC 12 EXAMPLE: np.where() to find indices
# ============================================================

import numpy as np

scores = np.array([55, 72, 48, 90, 65, 38, 85, 77, 60, 92])

# Find INDICES where scores > 80
indices = np.where(scores > 80)[0]
print("Indices where score > 80:", indices)      # Returns array of indices
print("Values at those indices  :", scores[indices]) # Get the actual values

print()

# Practical example: Find which students need remedial support
remedial_indices = np.where(scores < 50)[0]
print("Students needing remedial support (index):", remedial_indices)
print("Their scores:", scores[remedial_indices])

Indices where score > 80: [3 6 9]
Values at those indices  : [90 85 92]

Students needing remedial support (index): [2 5]
Their scores: [48 38]


---

## 🎉 Great Work! Task Complete!

---

### 📝 Summary — What You Learned Today

| # | Topic | Key Takeaway |
|---|-------|--------------|
| 1 | What is NumPy? | Foundation library for numerical computing in Python |
| 2 | NumPy vs Lists | NumPy is faster, uses less memory, supports math operations |
| 3 | Importing NumPy | `import numpy as np` — universal convention |
| 4 | Array Creation | `array()`, `arange()`, `zeros()`, `ones()`, `full()`, `linspace()` |
| 5 | Array Attributes | `ndim`, `shape`, `size`, `dtype` |
| 6 | 1D Indexing & Slicing | `arr[i]`, `arr[start:stop:step]` |
| 7 | 2D Arrays | Like a table — rows and columns |
| 8 | 2D Indexing & Slicing | `arr[row, col]`, `arr[:, col]`, `arr[r1:r2, c1:c2]` |
| 9 | Math Operations | Vectorized — apply to all elements without loops |
| 10 | Aggregation | `sum`, `mean`, `min`, `max`, `median`, `std`, `var` |
| 11 | Boolean Masking | Filter elements using conditions |
| 12 | `np.where()` | Vectorized if-else — replace/label values conditionally |

---

### 🚀 Coming Up Next — 

Stay tuned for **Next Day**, where we'll cover:
- Array reshaping
- Stacking and splitting arrays
- Random number generation
- Introduction to broadcasting

---

> 💡 **Pro Tip**: The best way to master NumPy is to **practice daily**.  
> Try re-solving the practice questions without looking at hints!  
> See you on Day 2! 🎯